### ISSUE TITLE
Social media links do not open in a new page

### ISSUE THREAD

**Issue by Arya-Gupta** [MLH-Fellowship/prep-portfolio-23.MAR.PREP.1#23]
In the footer, we have social media icons for LinkedIn, Instagram, Twitter, Facebook and YouTube. On being clicked, they do not open in a new tab. This might be annoying for a user who wants to open multiple links.

How to replicate:
- Visit the [pod portfolio](https://mlh-prep-23-mar-prep-1-portfolio.netlify.app/)
- Scroll down to the footer

![image](https://user-images.githubusercontent.com/84087089/224130529-3c0e38db-f330-4194-9235-8fdd71b02a47.png)

**Comment by sumana2001** [comment]
Hey @Arya-Gupta Good spot on the issue. Do you want to work on fixing this?

**Comment by Arya-Gupta** [comment]
Yes, that sounds great!
