### ISSUE TITLE
Add presentations made by fellows for Lightning Talks

### ISSUE THREAD

**Issue by Arya-Gupta** [MLH-Fellowship/prep-portfolio-23.MAR.PREP.1#29]
Every week, fellows present a topic to others through the help of a presentation for our Lightning Talk sessions. A link to these presentations could be displayed on the pod portfolio.

**Comment by sumana2001** [comment]
Since all the lightning talks won't be done till the last wednesday of the fellowship, I feel this section will need continuous updates. So for that reason I am closing the issue but it was definitely a good idea
