### ISSUE TITLE
Typo error in Jenna location and Ahmed's Image 💀

### ISSUE THREAD

**Issue by Garvit1809** [MLH-Fellowship/prep-portfolio-23.MAR.PREP.1#35]
There's a little mistake in the location and Ahmed's image is rotated
![image](https://user-images.githubusercontent.com/89806031/224398419-d6ac1771-3dea-4132-981e-d8e66faaf02f.png)

**Comment by sumana2001** [comment]
Good spot! If you would like to fix it, please go ahead
